import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import Layout from '../components/Layout'
import Meta from '../components/Meta'

const idKey=v=>String(v||'').normalize('NFKC').replace(/\s*#\s*/,'#').trim().toLowerCase()
const usable=p=>{const s=String(p?.name||'').trim(),i=s.lastIndexOf('#');return p?.hasRiotId!==false&&i>0&&i<s.length-1}
const pct=(n,d)=>d?Math.round(n/d*100):0
const playerLink=name=>{const i=name.lastIndexOf('#');return `/first-blood/player/${encodeURIComponent(name.slice(0,i))}?tag=${encodeURIComponent(name.slice(i+1))}`}

function aggregate(matches,profile){
  const map=new Map()
  for(const match of matches) for(const p of match.participants||[]){
    if(!usable(p))continue
    const k=idKey(p.name),x=map.get(k)||{name:p.name,games:0,firsts:0,deaths:0,pentas:0,kills:0,killGames:0,profile:k===idKey(profile)}
    x.games++;x.firsts+=!!p.gotFirstBlood;x.deaths+=!!p.wasFirstDeath;x.pentas+=Number(p.pentakills||0)
    if(p.kills!=null&&Number.isFinite(Number(p.kills))){x.kills+=Number(p.kills);x.killGames++} map.set(k,x)
  }
  return [...map.values()]
}
function Table({title,note,heads,rows}){return <section className="mb-10"><div className="flex items-end justify-between gap-4 mb-3"><h2 className="text-xl font-bold">{title}</h2><span className="text-xs text-hp-muted">{note}</span></div><div className="overflow-x-auto border border-hp-border rounded-lg bg-hp-surface"><table className="w-full min-w-[620px] text-sm"><thead><tr className="text-hp-muted text-xs uppercase">{heads.map(h=><th key={h} className="text-left px-4 py-3 border-b border-hp-border">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-b last:border-0 border-hp-border/60">{r.map((c,j)=><td key={j} className="px-4 py-3">{c}</td>)}</tr>):<tr><td colSpan={heads.length} className="px-4 py-6 text-hp-muted">No qualifying data yet.</td></tr>}</tbody></table></div></section>}
function CardBoard({eyebrow,title,description,cards,color='red'}){return <section className="mb-12"><p className="text-[10px] font-bold tracking-[.2em] text-hp-accent">{eyebrow}</p><h2 className="text-2xl font-bold mt-1">{title}</h2><p className="text-xs text-hp-muted mt-2 mb-4 max-w-3xl">{description}</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{cards.length?cards.map((x,i)=><article key={i} className={`min-h-36 p-5 bg-hp-surface border border-hp-border rounded-lg ${i===0?(color==='green'?'border-t-emerald-400':'border-t-red-500')+' border-t-2':''}`}><div className="text-[10px] font-bold tracking-widest text-hp-muted">{x.label}</div><div className="font-bold text-lg mt-2 truncate">{x.name}</div><div className="flex justify-between items-end mt-4"><div><strong className={`text-3xl ${color==='green'?'text-emerald-400':'text-red-500'}`}>{x.rate}%</strong><span className="block text-[10px] text-hp-muted mt-1">{x.rateLabel}</span></div><div className="text-right text-[11px] leading-5 text-hp-muted">{x.detail}</div></div></article>):<div className="sm:col-span-2 lg:col-span-3 border border-hp-border bg-hp-surface rounded-lg p-6 text-hp-muted">No qualifying data yet.</div>}</div></section>}
const rarityStyle={kSilver:'border-slate-400/70 text-slate-200',kGold:'border-amber-400/70 text-amber-200',kPrismatic:'border-fuchsia-400/70 text-fuchsia-200',kUnknown:'border-hp-border text-hp-muted'}
const rarityName=value=>String(value||'').replace(/^k/,'')||'Unknown'
function AugmentStrip({augments=[]}){const ordered=[...augments].sort((a,b)=>Number(a.order)-Number(b.order));if(!ordered.length)return null;return <div className="flex flex-wrap gap-1.5 mt-2">{ordered.map((augment,index)=><span key={`${augment.order}-${augment.id}`} title={`Choice ${augment.order||index+1}: ${augment.name} (${rarityName(augment.rarity)})`} className={`inline-flex items-center gap-1.5 rounded border bg-black/20 pr-2 text-[10px] ${rarityStyle[augment.rarity]||rarityStyle.kUnknown}`}><span className="pl-1.5 font-bold text-hp-muted">{augment.order||index+1}</span><img src={`/first-blood/augments/${Number(augment.id)}.png`} alt="" loading="lazy" className="w-7 h-7 object-cover"/><span className="hidden lg:inline max-w-32 truncate">{augment.name}</span></span>)}</div>}

export default function FirstBlood(){
  const {gameName}=useParams(),[query]=useSearchParams(),navigate=useNavigate()
  const [name,setName]=useState(gameName?decodeURIComponent(gameName):''),[tag,setTag]=useState(query.get('tag')||'')
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[showAll,setShowAll]=useState(false)
  useEffect(()=>{if(!gameName||!query.get('tag'))return;setLoading(true);setError('');fetch(`/.netlify/functions/first-blood-player?gameName=${encodeURIComponent(decodeURIComponent(gameName))}&tagLine=${encodeURIComponent(query.get('tag'))}`).then(async r=>{const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw Error(`Player service temporarily unavailable (${r.status||'no response'}); try again shortly`)}if(!r.ok)throw Error(d.error||`Could not load player history (${r.status})`);return d}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[gameName,query])
  const stats=useMemo(()=>aggregate(data?.matches||[],data?.player?.riotId),[data])
  const me=useMemo(()=>{const key=idKey(data?.player?.riotId);return (data?.matches||[]).map(m=>({m,p:(m.participants||[]).find(p=>idKey(p.name)===key)})).filter(x=>x.p)},[data])
  const teammates=useMemo(()=>{const map=new Map();for(const {m,p:meP} of me){if(typeof meP.won!=='boolean'||!meP.team)continue;for(const p of m.participants||[]){if(!usable(p)||idKey(p.name)===idKey(meP.name)||p.team!==meP.team)continue;const k=idKey(p.name),x=map.get(k)||{name:p.name,games:0,wins:0};x.games++;x.wins+=meP.won;map.set(k,x)}}return [...map.values()]},[me])
  const firsts=me.filter(x=>x.p.gotFirstBlood).length,firstDeaths=me.filter(x=>x.p.wasFirstDeath).length,completed=me.filter(x=>typeof x.p.won==='boolean'),wins=completed.filter(x=>x.p.won).length
  const link=n=><Link className="font-semibold hover:text-hp-accent" to={playerLink(n)}>{n}</Link>
  const riskCards=useMemo(()=>{const appearances=stats.reduce((n,x)=>n+x.games,0),deaths=stats.reduce((n,x)=>n+x.deaths,0),base=appearances?deaths/appearances:.1;return stats.filter(x=>x.games>=10).map(x=>({...x,score:(x.deaths+base*10)/(x.games+10)})).sort((a,b)=>b.score-a.score||b.games-a.games).slice(0,15).map((x,i)=>({name:link(x.name),label:`#${i+1} · ${x.games} GAMES`,rate:pct(x.deaths,x.games),rateLabel:'FIRST-DEATH RATE',detail:<>{x.deaths} first deaths<br/>{Math.round(x.score*100)}% ranking score</>}))},[stats])
  const winCards=useMemo(()=>{const games=teammates.reduce((n,x)=>n+x.games,0),wins=teammates.reduce((n,x)=>n+x.wins,0),base=games?wins/games:.5;const ranked=teammates.map(x=>({...x,score:(x.wins+base*10)/(x.games+10),provisional:x.games<10}));return [...ranked.filter(x=>!x.provisional).sort((a,b)=>b.score-a.score||b.games-a.games),...ranked.filter(x=>x.provisional).sort((a,b)=>b.games-a.games||b.score-a.score)].slice(0,15).map((x,i)=>({name:link(x.name),label:`${x.provisional?'PROVISIONAL':`#${i+1}`} · ${x.games} GAMES TOGETHER`,rate:pct(x.wins,x.games),rateLabel:'WIN RATE WITH',detail:<>{x.wins} wins<br/>{Math.round(x.score*100)}% ranking score</>}))},[teammates])
  const submit=e=>{e.preventDefault();if(name.trim()&&tag.trim())navigate(`/first-blood/player/${encodeURIComponent(name.trim())}?tag=${encodeURIComponent(tag.replace(/^#/,'').trim())}`)}
  return <Layout><Meta title="First Blood — ARAM Mayhem" description="ARAM Mayhem first blood, first death, win rate, and teammate statistics."/><div className="mb-10"><p className="text-xs font-bold tracking-[.2em] text-hp-accent">ARAM: MAYHEM · QUEUE 2400</p><h1 className="text-4xl sm:text-6xl font-black tracking-tight mt-3">Who drew <span className="text-red-500">first blood?</span></h1><p className="text-hp-muted mt-4 max-w-2xl">Search any player captured by the First Blood recorders.</p><form onSubmit={submit} className="mt-6 flex flex-col sm:flex-row bg-hp-surface border border-hp-border rounded-lg overflow-hidden max-w-3xl"><input className="flex-1 bg-transparent px-5 py-4 outline-none" value={name} onChange={e=>setName(e.target.value)} placeholder="Player name"/><div className="flex items-center border-t sm:border-t-0 sm:border-l border-hp-border px-4"><b className="text-hp-muted">#</b><input className="w-24 bg-transparent px-2 py-4 outline-none" value={tag} onChange={e=>setTag(e.target.value)} placeholder="NA1"/></div><button className="bg-red-500 hover:bg-red-400 text-white font-bold px-7 py-4">Search player</button></form>{error&&<p className="text-red-400 mt-3">{error}</p>}</div>
  {loading&&<p className="text-hp-muted">Loading player history…</p>}{data&&<><div className="flex justify-between items-end border-t border-hp-border pt-8"><div><p className="text-xs tracking-widest text-hp-accent">PLAYER REPORT</p><h2 className="text-3xl font-bold mt-1">{data.player.riotId}</h2></div><span className="text-xs text-hp-muted">{me.length} MAYHEM MATCHES</span></div><div className="grid grid-cols-2 lg:grid-cols-5 gap-3 my-7">{[['First-blood rate',`${pct(firsts,me.length)}%`],['First bloods',firsts],['First deaths',firstDeaths],['Not involved',me.length-firsts-firstDeaths],['Win rate',completed.length?`${pct(wins,completed.length)}%`:'—']].map(([a,b],i)=><div key={a} className={`p-5 bg-hp-surface border border-hp-border rounded-lg ${i===0?'border-t-red-500 border-t-2':''}`}><p className="text-xs text-hp-muted">{a}</p><strong className="text-3xl block mt-2">{b}</strong></div>)}</div>
  <Table title="Most played players" note={showAll?'Showing everyone':'Top 10'} heads={['Player','Games','First kills','First deaths','FB rate']} rows={stats.sort((a,b)=>b.games-a.games||b.firsts-a.firsts).slice(0,showAll?undefined:10).map(x=>[link(x.name),x.games,x.firsts,x.deaths,`${pct(x.firsts,x.games)}%`])}/>{stats.length>10&&<button onClick={()=>setShowAll(!showAll)} className="-mt-8 mb-10 text-sm text-hp-accent">{showAll?'Show top 10':'Show more players'}</button>}
  <CardBoard eyebrow="FIRST DEATH RISK" title="Who gets caught first?" description="Top 15 ranked by a sample-adjusted first-death rate. Players need at least 10 recorded games to qualify." cards={riskCards}/>
  <CardBoard eyebrow="TEAMMATE WIN RATE" title="Who do I win with?" description="Top 15 teammates. Qualified players rank by sample-adjusted win rate; lower-sample teammates fill remaining spots as provisional." cards={winCards} color="green"/>
  <Table title="Who draws first blood?" note="Top 10" heads={['Player','Games','First kills','Rate']} rows={stats.filter(x=>x.firsts).sort((a,b)=>b.firsts-a.firsts).slice(0,10).map(x=>[link(x.name),x.games,x.firsts,`${pct(x.firsts,x.games)}%`])}/>
  <Table title="Pentakill leaders" note="Top 10" heads={['Player','Games','Pentakills','Rate']} rows={stats.filter(x=>x.pentas).sort((a,b)=>b.pentas-a.pentas).slice(0,10).map(x=>[link(x.name),x.games,x.pentas,`${pct(x.pentas,x.games)}%`])}/>
  <Table title="Average kills per game" note="Sorted by tracked games, then total kills" heads={['Player','Tracked games','Total kills','Average']} rows={stats.filter(x=>x.killGames).sort((a,b)=>b.killGames-a.killGames||b.kills-a.kills).slice(0,10).map(x=>[link(x.name),x.killGames,x.kills,(x.kills/x.killGames).toFixed(1)])}/>
  <section><p className="text-[10px] font-bold tracking-[.2em] text-hp-accent">MATCH HISTORY</p><h2 className="text-2xl font-bold mt-1 mb-4">Recent games</h2><div className="space-y-2">{me.slice(0,25).map(({m,p})=>{const first=p.gotFirstBlood,death=p.wasFirstDeath,result=typeof p.won==='boolean'?(p.won?'VICTORY':'DEFEAT'):'RECORDED';return <article key={m.id} className="grid grid-cols-[6px_90px_1fr] sm:grid-cols-[6px_100px_1fr_150px] items-stretch min-h-24 border border-hp-border rounded-lg bg-hp-surface overflow-hidden"><span className={`h-full ${first?'bg-red-500':'bg-hp-border'}`}/><div className="px-4 self-center"><strong className={p.won?'text-emerald-400':''}>{result}</strong><small className="block text-hp-muted mt-1">{new Date(m.createdAt).toLocaleDateString()}</small></div><div className="py-3 self-center min-w-0"><strong>{p.champion||m.champion||'Unknown'}</strong><small className="block text-hp-muted mt-1">ARAM: Mayhem</small><AugmentStrip augments={p.augments}/></div><div className={`hidden sm:block self-center px-3 text-xs font-bold ${first?'text-red-500':'text-hp-muted'}`}>{first?'FIRST BLOOD':death?'FIRST DEATH':'NOT INVOLVED'}</div></article>})}</div></section></>}</Layout>
}
